### ISSUE TITLE
logikm配置了LDAP, 登陆没任何日志, 登陆报错:  ldap authentication failed

### ISSUE THREAD

**Issue by XzBuleSky** [didi/KnowStreaming#492]
你好, 我尝试接入LDAP服务, 重启服务使用LDAP用户登录, 页面报错:  ldap authentication failed  但日志没任何返回信息.  我这些配置在其他服务都可以正常接入LDAP服务, 比如jumpserver、yearning、grafana等等服务

```
account:
  jump-login:
    gateway-api: false            # 网关接口
    third-part-api: false         # 第三方接口
  ldap:
    enabled: True
    url: ldap://xxxx.xxxx.cn:389/
    basedn: dc=xxxxx,dc=xxxx
    factory: com.sun.jndi.ldap.LdapCtxFactory
    filter: sAMAccountName
    security:
      authentication: simple
      principal: uid=read,ou=xxxx,dc=xxxx,dc=cn
      credentials: xxxxx
    auth-user-registration: true
    auth-user-registration-role: normal
```
这个filter不清楚该填什么, 如果我填写以下配置,  就有报错信息返回
配置
```
filter:  
(&(uid={0})(|(memberof=cn=xxx,ou=xxx,dc=xx,dc=xxx)(memberof=cn=xxxx,ou=xxxx,dc=xxx,dc=xxx)))
```

返回错误:
```
javax.naming.directory.InvalidSearchFilterException: Missing 'equals'
```

当前显示的报错应该是找不到用户, 但我使用ldapsearch 指定了fliter是可以查询到自己的用户信息
