### ISSUE TITLE
使用已有的ElasticSearch(7.6.x)调整 values.yaml参数建议

### ISSUE THREAD

**Issue by AIMWLI** [didi/KnowStreaming#547]
生产现有es带密码认证集群 (xpack.security.enabled: true)
helm安装 value.yaml中参数如下:

```
   elasticsearch:
    enabled: false
    esClientAddress: 10.201.xxx.xx
    esProt: 9200
```
目前临时解决方案只能再搭一套冗余不带认证的es集群 (xpack.security.enabled: false)

经查阅目前不支持密码认证
```{{ if .Values.elasticsearch.enabled }}
esaddr=elasticsearch-master
port=9200
{{- else }}
esaddr={{ .Values.elasticsearch.esClientAddress }}
port={{ .Values.elasticsearch.esProt }}
{{- end }}
```

建议做成可选参数, 会更加友好呢
1. 冗余es集群, 有降低成本的空间
2. 如果从解耦合的角度出发, 单独一套运维环境这样也ok
