### ISSUE TITLE
访问es需要用户名和密码，请问如何配置

### ISSUE THREAD

**Issue by hilbert36** [didi/KnowStreaming#639]
# ES客户端配置
es:
  client:
    address: pmonitor.xxx.com:9200
    client-cnt: 10
    io-thread-cnt: 2
    max-retry-cnt: 5

没有指定用户名和密码报错：
ERROR com.didiglobal.logi.elasticsearch.client.ESClient - ESClient_sendRequest||cluster=elasticsearch||req=ESIndicesPutIndexRequest||url=/ks_kafka_topic_metric_2022-09-26||cost=5
org.elasticsearch.client.ResponseException: method [PUT], host [http://10.247.4.100:9200], URI [/ks_kafka_topic_metric_2022-09-26], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"invalid basic authentication header value","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"invalid basic authentication header value","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

**Comment by ZQKC** [comment]
> # ES客户端配置
> es: client: address: pmonitor.xxx.com:9200 client-cnt: 10 io-thread-cnt: 2 max-retry-cnt: 5
> 
> 没有指定用户名和密码报错： ERROR com.didiglobal.logi.elasticsearch.client.ESClient - ESClient_sendRequest||cluster=elasticsearch||req=ESIndicesPutIndexRequest||url=/ks_kafka_topic_metric_2022-09-26||cost=5 org.elasticsearch.client.ResponseException: method [PUT], host [http://10.247.4.100:9200], URI [/ks_kafka_topic_metric_2022-09-26], status line [HTTP/1.1 401 Unauthorized] {"error":{"root_cause":[{"type":"security_exception","reason":"invalid basic authentication header value","header":{"WWW-Authenticate":"Basic realm="security" charset="UTF-8""}}],"type":"security_exception","reason":"invalid basic authentication header value","header":{"WWW-Authenticate":"Basic realm="security" charset="UTF-8""}},"status":401}

你们客户端的密码是如何配置的？
```
es:
  client:
    address: pmonitor.xxx.com:9200
    pass: xxxx
    client-cnt: 10
    io-thread-cnt: 2
    max-retry-cnt: 5
```
这里的pass字段可以试着配置为用户名密码看是否可以连接上

**Comment by hilbert36** [comment]
address: pmonitor.xxx.com:9200
user:xxxx   或者 username:xxx
pass: xxxx  或者 password:xxx
上面几种名称都试了，都不行，看官方文档里面也没有

**Comment by ZQKC** [comment]
> es:
>   client:
>     address: pmonitor.xxx.com:9200
>     pass: xxxx
>     client-cnt: 10
>     io-thread-cnt: 2
>     max-retry-cnt: 5

按照如下对ES进行配置，其中pass字段的内容，填写为`username:password`，避免你的账号密码为admin/admin，则这里的pass填写的内容为`admin:admin`，试一下这种方式看是否可以。
```
es:
  client:
    address: pmonitor.xxx.com:9200
    pass: xxxx
    client-cnt: 10
    io-thread-cnt: 2
    max-retry-cnt: 5
```
