### ISSUE TITLE
Docker Compose 部署后登陆时弹窗报网络错误并不能登陆

### ISSUE THREAD

**Issue by thuanghai** [didi/KnowStreaming#852]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.2 </font>
* Operating System version :  <font size=4 color =red> RockyLinux 9.1 </font>
* Docker version : <font size=4 color =red> 20.10.22 </font>
* Docker Compose version : <font size=4 color =red> 2.14.1 </font>

### 重现该问题的步骤

1. 按说明文档进行容器化部署，因为时内网环境，所以只是修改了 image 仓库地址参数。
   
2. 再防火墙添加暴露端口 
```
sudo firewall-cmd --add-port=80/tcp --permanent
sudo firewall-cmd --reload
```

### 预期结果

输入默认的用户名后应该进入初始界面

### 实际结果

在登陆界面出现网络错误弹窗

首先查看knowstreaming-ui日志(docker logs knowstreaming-ui)，报错：
```
...[error] 20#20: *1 connect() failed (111: Connection refused) while connecting to up stream
```
再查看knowstreaming-manager日志(docker logs knowstreaming-manager)，报错：
```
Cause by: org.apache.ibatis.exceptions.PersistenceExceptions:
### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=knowstreaming-mysql)(port=3306)(type=primary). Connection refused (Connection refused)
### The error my exist in com/xiaojukeji/know/streaming/km/persistence/mysql/km/KmNodeDAO.java (best guess)
### The error my involve com.xiaojukeji.know.streaming.km.persistence.mysql.km.KmNodeDAO.selectList
### The error occurred while executing a query
......
```

**Comment by wangdongfang-aden** [comment]
> Connection refused

**Comment by wangdongfang-aden** [comment]
建议关闭一下防火墙再测试一下

**Comment by thuanghai** [comment]
> 建议关闭一下防火墙再测试一下

周一测试下，但是我还是想说，这个docker compose的部署走的是docker内部网络，跟主机的防火墙没什么关系吧。

**Comment by haoqi123** [comment]
可否贴一下Docker Compose 部署的文件？

**Comment by thuanghai** [comment]
> 可否贴一下Docker Compose 部署的文件？
```
services:

  # *不要调整knowstreaming-manager服务名称，ui中会用到
  knowstreaming-manager:
    image: registry.xxx.org/knowstreaming/knowstreaming-manager:0.7.0
    container_name: knowstreaming-manager
    privileged: true
    restart: always
    depends_on:
      - elasticsearch-single
      - knowstreaming-mysql
    expose:
      - 80
    command:
      - /bin/sh
      - /ks-start.sh
    environment:
      TZ: Asia/Shanghai
      # mysql服务地址
      SERVER_MYSQL_ADDRESS: knowstreaming-mysql:3306
      # mysql数据库名
      SERVER_MYSQL_DB: know_streaming
      # mysql用户名
      SERVER_MYSQL_USER: root
      # mysql用户密码
      SERVER_MYSQL_PASSWORD: admin
      # es服务地址
      SERVER_ES_ADDRESS: elasticsearch-single:9200
      # 服务JVM参数
      JAVA_OPTS: -Xmx1g -Xms1g
      # 对于kafka中ADVERTISED_LISTENERS填写的hostname可以通过该方式完成
#    extra_hosts:
#      - "hostname:x.x.x.x"
      # 服务日志路径
#    volumes:
#      - /ks/manage/log:/logs

  knowstreaming-ui:
    image: registry.xxx.org/knowstreaming/knowstreaming-ui:0.7.0
    container_name: knowstreaming-ui
    restart: always
    ports:
      - '80:80'
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - knowstreaming-manager
#    extra_hosts:
#      - "hostname:x.x.x.x"

  elasticsearch-single:
    image: registry.xxx.org/library/elasticsearch:7.17.3
    container_name: elasticsearch-single
    restart: always
    expose:
      - 9200
      - 9300
    #ports:
    #  - '9200:9200'
    #  - '9300:9300'
    environment:
      TZ: Asia/Shanghai
      # es的JVM参数
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # 单节点配置，多节点集群参考 https://www.elastic.co/guide/en/elasticsearch/reference/7.6/docker.html#docker-compose-file
      discovery.type: single-node
      # 数据持久化路径
#    volumes:
#      - /ks/es/data:/usr/share/elasticsearch/data

  # es初始��服务，与manager使用同一镜像
  # 首次启动es需初始化模版和索引,后续会自动创建
  knowstreaming-init:
    image: registry.xxx.org/knowstreaming/knowstreaming-manager:0.7.0
    container_name: knowstreaming-init
    depends_on:
      - elasticsearch-single
    command:
      - /bin/bash
      - /es_template_create.sh
    environment:
      TZ: Asia/Shanghai
      # es服务地址
      SERVER_ES_ADDRESS: elasticsearch-single:9200

  knowstreaming-mysql:
    image: registry.xxx.org/knowstreaming/knowstreaming-mysql:0.7.0
    container_name: knowstreaming-mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      # root 用户密码
      MYSQL_ROOT_PASSWORD: admin
      # 初始化时创建的数据库名称
      MYSQL_DATABASE: know_streaming
      # 通配所有host,可以访问远程
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306
    #ports:
    #  - '3306:3306'
      # 数据持久化路径
#    volumes:
#      - /ks/mysql/data:/data/mysql
```
registry.xxx.org 是我内部网络的私有仓库，没有问题的

**Comment by dolphinsboy** [comment]
使用如下的docker-compose.yml进行解决

```
version: "2"
services:
  # *不要调整knowstreaming-manager服务名称，ui中会用到
  knowstreaming-manager:
    image: knowstreaming/knowstreaming-manager:latest
    container_name: knowstreaming-manager
    privileged: true
    restart: always
    depends_on:
      - elasticsearch-single
      - knowstreaming-mysql
    expose:
      - 80
    networks:
      - my_net
    command:
      - /bin/sh
      - /ks-start.sh
    environment:
      TZ: Asia/Shanghai
      # mysql服务地址
      SERVER_MYSQL_ADDRESS: knowstreaming-mysql:3306
      # mysql数据库名
      SERVER_MYSQL_DB: know_streaming
      # mysql用户名
      SERVER_MYSQL_USER: root
      # mysql用户密码
      SERVER_MYSQL_PASSWORD: admin2022_
      # es服务地址
      SERVER_ES_ADDRESS: elasticsearch-single:9200
      # 服务JVM参数
      JAVA_OPTS: -Xmx1g -Xms1g
      # 对于kafka中ADVERTISED_LISTENERS填写的hostname可以通过该方式完成
#    extra_hosts:
#      - "hostname:x.x.x.x"
      # 服务日志路径
#    volumes:
#      - /ks/manage/log:/logs
  knowstreaming-ui:
    image: knowstreaming/knowstreaming-ui:latest
    container_name: knowstreaming-ui
    restart: always
    ports:
      - '80:80'
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - knowstreaming-manager
    networks:
      - my_net
#    extra_hosts:
#      - "hostname:x.x.x.x"
  elasticsearch-single:
    image: docker.io/library/elasticsearch:7.6.2
    container_name: elasticsearch-single
    restart: always
    expose:
      - 9200
      - 9300
    networks:
      - my_net
#    ports:
#      - '9200:9200'
#      - '9300:9300'
    environment:
      TZ: Asia/Shanghai
      # es的JVM参数
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # 单节点配置，多节点集群参考 https://www.elastic.co/guide/en/elasticsearch/reference/7.6/docker.html#docker-compose-file
      discovery.type: single-node
      # 数据持久化路径
#    volumes:
#      - /ks/es/data:/usr/share/elasticsearch/data

  # es初始化服务，与manager使用同一镜像
  # 首次启动es需初始化模版和索引,后续会自动创建
  knowstreaming-init:
    image: knowstreaming/knowstreaming-manager:latest
    container_name: knowstreaming-init
    depends_on:
      - elasticsearch-single
    command:
      - /bin/bash
      - /es_template_create.sh
    networks:
      - my_net
    environment:
      TZ: Asia/Shanghai
      # es服务地址
      SERVER_ES_ADDRESS: elasticsearch-single:9200

  knowstreaming-mysql:
    image: knowstreaming/knowstreaming-mysql:latest
    container_name: knowstreaming-mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      # root 用户密码
      MYSQL_ROOT_PASSWORD: admin2022_
      # 初始化时创建的数据库名称
      MYSQL_DATABASE: know_streaming
      # 通配所有host,可以访问远程
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306
    networks:
      - my_net
#    ports:
#      - '3306:3306'
      # 数据持久化路径
#    volumes:
#      - /ks/mysql/data:/data/mysql
#
networks:
  my_net:
    driver: bridge
```
