### ISSUE TITLE
Ldap配置登录问题 官网没有详细配置说明

### ISSUE THREAD

**Issue by jy00278439** [didi/KnowStreaming#888]
## 环境信息
CentOS7.9
KnowStreaming-3.2.0.tar.gz
WindowsAD

![55f7ee9489b73867de34b9cc76aa71e](https://user-images.githubusercontent.com/3014548/217416065-7a466069-fdcd-4c7e-9e9c-2080dde696c8.png)

## 问题描述
- 参考文档配置LDAP后

## 相关配置
```bash
account:
  ldap:
    enabled: true
    url: ldap://172.31.1.6:389/
    basedn: DC=senz,DC=local
    factory: com.sun.jndi.ldap.LdapCtxFactory
    filter: sAMAccountName
    security:
      authentication: simple
      principal: CN=search,DC=senz,DC=local
      credentials: AiQK1[LeV3gw
    auth-user-registration: true
    auth-user-registration-role: normal
```

![image](https://user-images.githubusercontent.com/3014548/217417108-9bca80d9-1d3b-4004-8449-687d1bc736d0.png)

**Comment by ZQKC** [comment]
试一下按照下面的例子修改一下看是否可以：
```
account:
  ldap:
    url: ldap://172.31.1.6:389/
    basedn: DC=senz,DC=local
    factory: com.sun.jndi.ldap.LdapCtxFactory
    filter: sAMAccountName
    security:
      authentication: simple
      principal: CN=search,DC=senz,DC=local
      credentials: AiQK1[LeV3gw
    auth-user-registration: false
    auth-user-registration-role: 1677

spring:
  logi-security:
    login-extend-bean-name: ksLdapLoginService # 这个位置的配置也需要修改一下
```
